"""suppliers: supplier + supplier_private

Revision ID: 4c803f8c6ddb
Revises: a7fe07680a40
Create Date: 2026-07-17 23:21:21.548431

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c803f8c6ddb"
down_revision: str | Sequence[str] | None = "a7fe07680a40"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suppliers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column(
            "legal_type",
            sa.Enum(
                "individual",
                "legal",
                name="legaltype",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("district_id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("has_delivery", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("tg_chat_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "paused",
                name="supplierstatus",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("response_median_sec", sa.Integer(), nullable=True),
        sa.Column("requests_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["district_id"], ["districts.id"], name=op.f("fk_suppliers_district_id_districts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
        sa.UniqueConstraint("tg_chat_id", name=op.f("uq_suppliers_tg_chat_id")),
    )
    op.create_index(op.f("ix_suppliers_district_id"), "suppliers", ["district_id"], unique=False)
    op.create_table(
        "supplier_private",
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("passport", sa.String(length=50), nullable=True),
        sa.Column("inn", sa.String(length=20), nullable=True),
        sa.Column("requisites", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_supplier_private_supplier_id_suppliers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("supplier_id", name=op.f("pk_supplier_private")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("supplier_private")
    op.drop_index(op.f("ix_suppliers_district_id"), table_name="suppliers")
    op.drop_table("suppliers")
    # ### end Alembic commands ###
