"""users: user + offer_acceptances

Revision ID: a8923e926319
Revises: 4c803f8c6ddb
Create Date: 2026-07-17 23:24:32.625181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8923e926319'
down_revision: Union[str, Sequence[str], None] = '4c803f8c6ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('language', sa.Enum('ru', 'uz', name='userlanguage', native_enum=False, create_constraint=True, length=8), server_default='ru', nullable=False),
    sa.Column('client_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('deals_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_table('offer_acceptances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('offer_version', sa.String(length=50), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(user_id IS NULL) <> (supplier_id IS NULL)', name=op.f('ck_offer_acceptances_actor')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_offer_acceptances_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_offer_acceptances_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offer_acceptances'))
    )
    op.create_index(op.f('ix_offer_acceptances_supplier_id'), 'offer_acceptances', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_offer_acceptances_user_id'), 'offer_acceptances', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offer_acceptances_user_id'), table_name='offer_acceptances')
    op.drop_index(op.f('ix_offer_acceptances_supplier_id'), table_name='offer_acceptances')
    op.drop_table('offer_acceptances')
    op.drop_table('users')
    # ### end Alembic commands ###
