"""catalog: listings, listing_photos, units

Revision ID: ba896676a847
Revises: 0d24cd502630
Create Date: 2026-07-18 12:48:54.085778

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba896676a847"
down_revision: str | Sequence[str] | None = "0d24cd502630"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price_per_day", sa.BigInteger(), nullable=False),
        sa.Column(
            "deposit_kind",
            sa.Enum(
                "money",
                "passport",
                "none",
                name="depositkind",
                native_enum=False,
                create_constraint=True,
                length=12,
            ),
            server_default="none",
            nullable=False,
        ),
        sa.Column("deposit_amount", sa.BigInteger(), nullable=True),
        sa.Column("quantity", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "moderation",
                "active",
                "hidden",
                name="listingstatus",
                native_enum=False,
                create_constraint=True,
                length=12,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("fits_photo_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_listings_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_listings_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_listings_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listings")),
        sa.UniqueConstraint("slug", name=op.f("uq_listings_slug")),
    )
    op.create_index(
        "ix_listings_category_status", "listings", ["category_id", "status"], unique=False
    )
    op.create_index(op.f("ix_listings_supplier_id"), "listings", ["supplier_id"], unique=False)
    op.create_table(
        "listing_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("sort", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_listing_photos_listing_id_listings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_photos")),
    )
    op.create_index(
        op.f("ix_listing_photos_listing_id"), "listing_photos", ["listing_id"], unique=False
    )
    op.create_table(
        "units",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("inventory_no", sa.String(length=50), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "repair",
                "retired",
                name="unitstatus",
                native_enum=False,
                create_constraint=True,
                length=12,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_units_listing_id_listings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units")),
    )
    op.create_index(op.f("ix_units_listing_id"), "units", ["listing_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_units_listing_id"), table_name="units")
    op.drop_table("units")
    op.drop_index(op.f("ix_listing_photos_listing_id"), table_name="listing_photos")
    op.drop_table("listing_photos")
    op.drop_index(op.f("ix_listings_supplier_id"), table_name="listings")
    op.drop_index("ix_listings_category_status", table_name="listings")
    op.drop_table("listings")
    # ### end Alembic commands ###
